version: '3.8'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - mosquitto
    restart: unless-stopped
    network_mode: host
    healthcheck:
        test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
        interval: 30s
        timeout: 10s
        retries: 6

  node-red:
    container_name: node-red
    image: nodered/node-red:latest-10
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - homeassistant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:1880"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    external:
      name: default-network
