version: "3.8"

services:

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
    volumes:
      - ./syncthing/config:/config
      - ${HOME}:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "880:80/tcp"
  #     - "8443:443/tcp"
  #   environment:
  #     TZ: 'Europe/Berlin'
  #     WEBPASSWORD: ${PIHOLE_PASSWORD}
  #     DNS1: 10.0.0.1
  #     DNS2: 10.0.0.1
  #     DNSSEC: 'true'
  #   volumes:
  #     - ./pihole/etc-pihole/:/etc/pihole/
  #     - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
  #     - ./pihole/var-log/pihole.log:/var/log/pihole.log
  #   dns:
  #     - 10.0.0.1
  #   restart: unless-stopped

networks:
  default:
    external:
      name: default-network