version: "3.8"

services:

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - UMASK_SET=022
    volumes:
      - ./syncthing/config:/config
      - ${HOME}:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

networks:
  default:
    external:
      name: default-network